name: Publish

on:
  push:
    tags:
      - '*'
jobs:
  build:
    name: Publish binaries
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run package-win --if-present
    - run: npm run create-instaler-win --if-present
    
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: release-builds/windows-installer/RELEASES
        asset_name: RELEASES
        tag: ${{ github.ref }}
        overwrite: true
        body: ""
