name: Publish

on:
  push:
    tags:
      - '*'
jobs:
  build:
    name: Publish binaries
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
        
    - name: Get package.json version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@master
    
    - name: Package Windows application
      run: npm run package-win --if-present
    - name: Create Windows installer
      run: npm run create-installer-win --if-present
    
    - name: Upload RELEASES
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: release-builds/windows-installer/RELEASES
        asset_name: RELEASES
        tag: ${{ github.ref }}
        overwrite: true
        body: ""
    - name: Upload NUPKG
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: release-builds/windows-installer/StreamStatsWidgetsOverlayApp-${{ steps.package-version.outputs.current-version}}-full.nupkg
        asset_name: StreamStatsWidgetsOverlayApp-${{ steps.package-version.outputs.current-version}}-full.nupkg
        tag: ${{ github.ref }}
        overwrite: true
        body: ""
    - name: Upload DELTA NUPKG
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: release-builds/windows-installer/StreamStatsWidgetsOverlayApp-${{ steps.package-version.outputs.current-version}}-delta.nupkg
        asset_name: StreamStatsWidgetsOverlayApp-${{ steps.package-version.outputs.current-version}}-delta.nupkg
        tag: ${{ github.ref }}
        overwrite: true
        body: ""
    - name: Upload EXE
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: release-builds/windows-installer/StreamStatsWidgetsOverlayAppInstaller.exe
        asset_name: StreamStatsWidgetsOverlayAppInstaller.exe
        tag: ${{ github.ref }}
        overwrite: true
        body: ""
